export const MENU_ORIENTATION_VERTICAL = 'MENU_ORIENTATION_VERTICAL';
export const MENU_ORIENTATION_HORIZONTAL = 'MENU_ORIENTATION_HORIZONTAL';

//export const API_ADDRESS = 'http://localhost:8000/api/';

export const API_ADDRESS = 'http://bigtrouble-backend-heroku.herokuapp.com/api/';




/* Login reducers type */
export const JWT_TOKEN = 'JWT_TOKEN';
export const USER_ID = 'USER_ID';
export const USER_ROLE = 'USER_ROLE';

/* Product  */
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_ADD = 'ADD_PRODUCT';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_CLOSE_NOTIFICATION = 'PRODUCT_CLOSE_NOTIFICATION';
export const PRODUCT_ADD_ERROR = 'ADD_PRODUCT_ERROR';

/* User  */
export const USER_LIST = 'USER_LIST';

/* Account  */
export const ACCOUNT_LIST = 'ACCOUNT_LIST';

/* Reservation */
export const RESERVATION_FORM = 'RESERVATION_FORM';
export const RESERVATION_LIST = 'RESERVATION_LIST';
export const RESERVATION_EDIT = 'RESERVATION_EDIT';
export const RESERVATION_ADD = 'RESERVATION_ADD';
export const RESERVATION_DELETE = 'RESERVATION_DELETE';
export const RESERVATION_CLOSE_NOTIFICATION = 'RESERVATION_CLOSE_NOTIFICATION';
export const RESERVATION_ADD_ERROR = 'RESERVATION_ADD_ERROR';
export const RESERVATION_VALIDADE_SUCCESS = 'RESERVATION_VALIDADE_SUCCESS';


/* Announcement */
export const ANNOUNCEMENT_LIST = 'ANNOUNCEMENT_LIST';
export const ANNOUNCEMENT_ADD = 'ADD_ANNOUNCEMENT';
export const ANNOUNCEMENT_DELETE = 'ANNOUNCEMENT_DELETE';
export const ANNOUNCEMENT_CLOSE_NOTIFICATION = 'ANNOUNCEMENT_CLOSE_NOTIFICATION';
export const ANNOUNCEMENT_ADD_ERROR = 'ADD_ANNOUNCEMENT_ERROR';

/* Schedule*/
export const SCHEDULE_LIST = 'SCHEDULE_LIST';
export const SCHEDULE_ADD = 'ADD_SCHEDULE';
export const SCHEDULE_DELETE = 'SCHEDULE_DELETE';
export const SCHEDULE_CLOSE_NOTIFICATION = 'SCHEDULE_CLOSE_NOTIFICATION';
export const SCHEDULE_ADD_ERROR = 'ADD_SCHEDULE_ERROR';
export const SCHEDULE_CLEAR_WEEK = 'SCHEDULE_CLEAR_WEEK'

/* Availability */
export const AVAILABILITY_LIST = 'AVAILABILITY_LIST';
export const AVAILABILITY_ADD = 'ADD_AVAILABILITY';
export const AVAILABILITY_DELETE = 'AVAILABILITY_DELETE';
export const AVAILABILITY_CLOSE_NOTIFICATION = 'AVAILABILITY_CLOSE_NOTIFICATION';
export const AVAILABILITY_ADD_ERROR = 'ADD_AVAILABILITY_ERROR';
export const AVAILABILITY_LIST_CURRENT = 'AVAILABILITY_LIST_CURRENT';
export const AVAILABILITY_CLEAR_WEEK = 'AVAILABILILTY_CLEAR_WEEK'